abi_back/urls.py
from django.conf.urls import url
from django.contrib import admin

# NoQA
from django.views.generic import TemplateView

urlpatterns = [
    # Considere to remove this
    url(
        r'^admin/', admin.site.urls
    ),
    # NoQA
    url(
        r'^$', TemplateView.as_view(template_name="base.html")
    ),
    url(
        r'^authentication/',
        (
            "applications.authentication.urls",
            "authentication",
            ""
        )
    ),
    url(
        r'^core/',
        (
            "applications.core.urls",
            "core",
            ""
        )
    ),
    url(
        r'^appointments/',
        (
            "applications.appointments.urls",
            "appointments",
            ""
        )
    ),

    url(
        r'^api/v1/',
        (
            "abi_back.urls_api",
            "api",
            ""
        )
    ),
]

applications/appointments/forms.py
from django import forms

from . import (
    models
)


class Appointment(forms.ModelForm):
    class Meta:
        model = models.Appointment
        fields = (
            'patient_fk',
            'specialist_fk',
            'date'
        )

applications/core/forms.py
from django import forms

from . import (
    models
)


class Administrator(forms.ModelForm):
    class Meta:
        model = models.Administrator
        fields = [
            'username',
            'password'
        ]

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control  col-md-7 col-xs-12'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control  col-md-7 col-xs-12'})
        }

    def save(self, commit=True):
        """
        Custom save method for determine active and unactive users
        :param commit:
        :return:
        """
        user = super(Administrator, self).save(commit=False)
        if commit:
            user.is_active = True
            user.set_password(self.cleaned_data['password'])
            user.save()
        return user


class Specialist(Administrator):

    class Meta(Administrator.Meta):
        model = models.Specialist


class Patient(Administrator):

    class Meta(Administrator.Meta):
        model = models.Patient
        fields = [
            'username',
            'password',
            'specialist_fk'
        ]


class Secretary(Administrator):

    class Meta(Administrator.Meta):
        model = models.Secretary


class Machine(forms.ModelForm):
    class Meta:
        model = models.Machine
        fields = [
            'name',
            'description',
            'type',
            'code'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control  col-md-7 col-xs-12'}),
            'description': forms.TextInput(attrs={'class': 'form-control  col-md-7 col-xs-12'}),
            'type': forms.TextInput(attrs={'class': 'form-control  col-md-7 col-xs-12'}),
            'code': forms.TextInput(attrs={'class': 'form-control  col-md-7 col-xs-12'}),
        }


class Treatment(forms.ModelForm):
    class Meta:
        model = models.Treatment
        fields = '__all__'


class Procedure(forms.ModelForm):
    class Meta:
        model = models.Procedure
        fields = '__all__'


class ProcedureNoPatientNoSpecialist(forms.ModelForm):
    class Meta:
        model = models.Procedure
        fields = [
            'treatment_fk',
            'action'
        ]


class SimpleObservation(forms.ModelForm):
    class Meta:
        model = models.Observation
        fields = [
            'observation',
        ]


class MachineInstance(forms.ModelForm):
    class Meta:
        model = models.MachineInstance
        fields = '__all__'


class MachineInput(forms.ModelForm):
    class Meta:
        model = models.MachineInput
        fields = '__all__'

applications/core/views/base_view.py
from base import views as base_views


class BaseCreateView(base_views.BaseCreateView):
    template_name = "custom_create/create.html"

    def __init__(self, *args, **kwargs):
        super(BaseCreateView, self).__init__(*args, **kwargs)

class BaseUpdateView(base_views.BaseUpdateView):
    template_name = "custom_update/update.html"

    def __init__(self, *args, **kwargs):
        super(BaseUpdateView, self).__init__(*args, **kwargs)

class BaseDeleteView(base_views.BaseDeleteView):
    template_name = "custom_delete/delete.html"

    def __init__(self, *args, **kwargs):
        super(BaseDeleteView, self).__init__(*args, **kwargs)

templates/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Abi Medical | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css'%}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css'%}" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">

            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="/" class="site_title"><i class="fa fa-desktop"></i> <span>Abi Medical</span></a>
                    </div>

                    <div class="clearfix"></div>

                    {% if user.is_authenticated %}
                        <!-- menu profile quick info -->
                        <div class="profile clearfix">
                            <div class="profile_pic">
                                <img src="{% static 'images/img.jpg' %}" alt="..." class="img-circle profile_img">
                            </div>
                            <div class="profile_info">
                                <span>Bienvenido,</span>
                                <h2>{{ user }}</h2>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <!-- /menu profile quick info -->


                        <br />

                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            {% block menu %}
                                {% if request.tenant.name != 'Main Schema' %}
                                    {% include 'menu_tenant.html' %}
                                {% else %}
                                    {% include 'menu_admin.html' %}
                                {% endif %}
                            {% endblock %}
                        </div>
                        <!-- /sidebar menu -->

                        <!-- /menu footer buttons -->
                        <div class="sidebar-footer hidden-small">
                            <a data-toggle="tooltip" data-placement="top" title="Settings">
                                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Lock">
                                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'log_out' %}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                            </a>
                        </div>
                        <!-- /menu footer buttons -->
                    {% endif %}
                </div>

            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                                <li class="">
                                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <img src="{% static 'images/img.jpg' %}" alt="">{{ user }}
                                        <span class=" fa fa-angle-down"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                                        <li><a href="{% url 'log_out' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                    </ul>
                                </li>
                            {% endif %}


                        </ul>
                    </nav>
                </div>
            </div>

            <!-- /top navigation -->
        <!-- page content -->
        <div class="right_col" role="main">
            {% for message in messages %}
                <div class="alert alert-{{ message.level_tag }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    {{ message }}
                </div>
            {% endfor %}
            {% block content %}
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>ABI</h3>
                        </div>

                        <div class="title_right">
                            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search for...">
                                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2>Welcome to ABI</h2>
                                    <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    Add content to the page ...
                                </div>
                            </div>
                            {% if not user.is_authenticated %}
                            <a href="{% url 'log_in' %}">

                                <button class="btn btn-block btn-primary">
                                    {% trans 'Log In' %}
                                </button>
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endblock %}
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
            <div class="pull-right">
                Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>
</div>

<!-- jQuery -->
<script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
<!-- NProgress -->
<script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>

<!-- Custom Theme Scripts -->
<script src="{% static 'build/js/custom.min.js' %}"></script>
</body>
</html>

templates/base2.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Abi Medical | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css'%}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css'%}" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">

            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="/" class="site_title"><i class="fa fa-desktop"></i> <span>Abi Medical</span></a>
                    </div>

                    <div class="clearfix"></div>

                    {% if user.is_authenticated %}
                        <!-- menu profile quick info -->
                        <div class="profile clearfix">
                            <div class="profile_pic">
                                <img src="{% static 'images/img.jpg' %}" alt="..." class="img-circle profile_img">
                            </div>
                            <div class="profile_info">
                                <span>Bienvenido,</span>
                                <h2>{{ user }}</h2>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <!-- /menu profile quick info -->


                        <br />

                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            {% block menu %}
                                {% if request.tenant.name != 'Main Schema' %}
                                    {% include 'menu_tenant.html' %}
                                {% else %}
                                    {% include 'menu_admin.html' %}
                                {% endif %}
                            {% endblock %}
                        </div>
                        <!-- /sidebar menu -->

                        <!-- /menu footer buttons -->
                        <div class="sidebar-footer hidden-small">
                            <a data-toggle="tooltip" data-placement="top" title="Settings">
                                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Lock">
                                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'log_out' %}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                            </a>
                        </div>
                        <!-- /menu footer buttons -->
                    {% endif %}
                </div>

            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                                <li class="">
                                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <img src="{% static 'images/img.jpg' %}" alt="">{{ user }}
                                        <span class=" fa fa-angle-down"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                                        <li><a href="{% url 'log_out' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                    </ul>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>

        <!-- /top navigation -->
        <!-- page content -->
        <div class="right_col" role="main">
            {% for message in messages %}
                <div class="alert alert-{{ message.level_tag }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    {{ message }}
                </div>
            {% endfor %}
            {% block content %}
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>ABI</h3>
                        </div>

                        <div class="title_right">
                            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search for...">
                                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2>Welcome to ABI</h2>
                                    <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    Add content to the page ...
                                </div>
                            </div>
                            {% if not user.is_authenticated %}
                            <a href="{% url 'log_in' %}">
                                <button class="btn btn-block btn-primary">
                                    {% trans 'Log In' %}
                                </button>
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endblock %}
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
            <div class="pull-right">
                Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>
</div>

<!-- jQuery -->
<script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
<!-- NProgress -->
<script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>

<!-- Custom Theme Scripts -->
<script src="{% static 'build/js/custom.min.js' %}"></script>
</body>
</html>

templates/menu_admin.html
{% load i18n %}
{% if user.is_staff %}
    <div class="menu_section">
        <h3>{% trans 'Settings' %}</h3>
        <ul class="nav side-menu">
            <li>
                <a>
                    <i class="fa fa-building"></i>
                    {% trans 'Tenants' %}
                    <span class="fa fa-chevron-down"></span>
                </a>
                <ul class="nav child_menu">
                    <li>
                        <a href="{% url 'TENANT_list' %}">
                            {% trans 'Tenants' %}
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
{% else %}

{% endif %}

templates/menu_tenant.html
{% load i18n %}
<div class="menu_section">
    <h3>{% trans 'Core' %}</h3>
    <ul class="nav side-menu">
        <li>
            <a>
                <i class="fa fa-user"></i>
                {% trans 'Users' %}
                <span class="fa fa-chevron-down"></span>
            </a>
            <ul class="nav child_menu">
                <li>
                    {% if perms.core.add_administrator %}
                        <a href="{% url 'ADMINISTRATOR_list' %}">
                            {% trans 'Administrators' %}
                        </a>
                    {% endif %}
                </li>
                <li>
                    {% if perms.core.add_specialist %}
                        <a href="{% url 'SPECIALIST_list' %}">
                            {% trans 'Specialists' %}
                        </a>
                    {% endif %}
                </li>
                <li>
                    {% if perms.core.add_patient %}
                        <a href="{% url 'PATIENT_list' %}">
                            {% trans 'Patients' %}
                        </a>
                    {% endif %}
                </li>
                <li>
                    {% if perms.core.add_secretary %}
                        <a href="{% url 'SECRETARY_list' %}">
                            {% trans 'Secretary' %}
                        </a>
                    {% endif %}
                </li>
            </ul>
        </li>
        <li>
            <a>
                <i class="fa fa-cogs"></i>
                {% trans 'Settings' %}
                <span class="fa fa-chevron-down"></span>
            </a>
            <ul class="nav child_menu">
                <li>
                    {% if perms.core.add_machine %}
                        <a href="{% url 'MACHINE_list' %}">
                            {% trans 'Machines' %}
                        </a>
                    {% endif %}
                </li>
                <li>
                    {% if perms.core.add_machine_instance %}
                        <a href="{% url 'MACHINEINSTANCE_list' %}">
                            {% trans 'Machine Instance' %}
                        </a>
                    {% endif %}
                </li>
                <li>
                    {% if perms.core.add_treatment %}
                        <a href="{% url 'TREATMENT_list' %}">
                            {% trans 'Treatment' %}
                        </a>
                    {% endif %}
                </li>
            </ul>
        </li>
        <li>
            <a>
                <i class="fa fa-cogs"></i>
                {% trans 'Appointments' %}
                <span class="fa fa-chevron-down"></span>
            </a>
            <ul class="nav child_menu">
                <li>
                    {% if perms.appointment.add_appointment %}
                        <a href="{% url 'APPOINTMENT_list' %}">
                            {% trans 'Appointments' %}
                        </a>
                    {% endif %}
                </li>
            </ul>
        </li>

    </ul>
</div>